# Generated by Django 3.2 on 2021-04-19 05:19

import crm.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_to_be_contacted', models.DateField(blank=True, editable=False, null=True)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('mobile_number', models.CharField(blank=True, max_length=8, null=True, validators=[crm.validators.mobile_number_validator])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_method', models.CharField(blank=True, choices=[('Phone Call', 'Phone Call'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Text', 'Text'), ('Do Not Contact', 'Do Not Contact')], help_text="This Customer's preferred method of contact.", max_length=50, null=True)),
                ('pdpa_agreed', models.BooleanField(help_text='Customer has agreed to PDPA rules.', verbose_name='PDPA Acknowledged')),
                ('deal_stage', models.CharField(blank=True, choices=[('interested', 'Interested'), ('collected sample pack', 'Collected Sample Pack'), ('contacted', 'Contacted'), ('appointment booked', 'Appointment Booked'), ('purchased', 'Purchased'), ('closed lost', 'Closed (Lost)'), ('closed won', 'Closed (Won)'), ('complained', 'Complained'), ('refund', 'Refund')], default='interested', max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff Member who served this customer.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.location')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
