# Generated by Django 3.2 on 2021-04-20 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_customer_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 20)),
        ),
    ]
