# Generated by Django 3.2 on 2021-04-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_customer_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
