# Generated by Django 3.2 on 2021-04-21 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20210420_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_to_be_contacted',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 28), help_text='DO NOT EDIT. Only change if the customer request to be contacted on a different day. Default is 7 days. ', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deal_stage',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('collected sample pack', 'Collected Sample Pack'), ('contacted', 'Contacted'), ('appointment booked', 'Appointment Booked'), ('closed lost', 'Closed (Lost)'), ('closed won', 'Closed (Won)'), ('complained', 'Complained'), ('refund', 'Refund')], default='interested', max_length=50, null=True),
        ),
    ]
