# Generated by Django 3.2 on 2021-04-22 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20210421_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_to_be_contacted',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 29), help_text='DO NOT EDIT. Only change if the customer request to be contacted on a different day. Default is 7 days. ', null=True),
        ),
    ]
