# Generated by Django 3.2 on 2021-04-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_customer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_method',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='do_not_contact',
            field=models.BooleanField(default=False),
        ),
    ]
