# Generated by Django 3.2 on 2021-04-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_customer_date_to_be_contacted'),
        ('crm', '0018_auto_20210422_2240'),
    ]

    operations = [
    ]
