# Generated by Django 3.2 on 2021-04-25 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_merge_20210423_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_to_be_contacted',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 2), help_text='DO NOT EDIT. Only change if the customer request to be contacted on a different day. Default is 7 days. ', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='do_not_contact',
            field=models.BooleanField(default=False, verbose_name='DO NOT CONTACT'),
        ),
    ]
