# Generated by Django 3.2 on 2021-04-30 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20210426_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_to_be_contacted',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 7), help_text='DO NOT EDIT. Only change if the customer request to be contacted on a different day. Default is 7 days. ', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deal_stage',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('collected sample pack', 'Collected Sample Pack'), ('contacted', 'Contacted'), ('appointment booked', 'Appointment Booked'), ('closed lost', 'Closed (Lost)'), ('closed won', 'Closed (Won)'), ('complained', 'Complained'), ('refund', 'Refund')], default='collected sample pack', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pdpa_agreed',
            field=models.BooleanField(default=True, help_text='Customer has agreed to PDPA rules.', verbose_name='PDPA Acknowledged'),
        ),
    ]
