# Generated by Django 3.2 on 2021-04-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20210430_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_add_date', models.DateField()),
                ('default_contact_date', models.DateField()),
            ],
        ),
    ]
