# Generated by Django 3.2 on 2021-04-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_crmadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmadmin',
            options={'verbose_name': 'CRM Admin Settings', 'verbose_name_plural': 'CRM Admin Settings'},
        ),
        migrations.AddField(
            model_name='crmadmin',
            name='use_defaults',
            field=models.BooleanField(default=False),
        ),
    ]
